dataset: cifar10
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 5
- 7
- 9
- 13
- 19
- 26
- 37
- 52
- 73
- 102
- 142
- 199
fidelity_single: 5
max_hpo_time: 3000
out_dir: p201-0
predictor: gcn
search_space: nasbench201
seed: 0
test_size: 200
train_size_list:
- 5
- 8
- 14
- 24
- 42
- 71
- 121
- 205
- 347
- 589
- 1000
train_size_single: 10
uniform_random: 1
