dataset: cifar10
experiment_type: single
fidelity_list:
- 1
- 2
- 3
- 4
- 5
- 7
- 10
- 13
- 17
- 23
- 30
- 40
- 54
- 71
- 95
fidelity_single: 95
max_hpo_time: 0
out_dir: p301-0
predictor: gcn
search_space: nasbench301
seed: 0
test_size: 200
train_size_list:
- 5
- 8
- 12
- 20
- 31
- 50
- 79
- 126
- 199
- 316
- 500
train_size_single: 200
uniform_random: 1
